### ISSUE TITLE
Unable to send json as payload

### ISSUE THREAD

**Issue by kuchta** [TypedProject/ts-httpexceptions#4]
Unfortunatelly using ts-httpexceptions I'm not able send back object (to be converted to json by middleware) as error content....

**Comment by Romakita** [comment]
Hi @kuchta 
It's dependend of the used framework ?

For example with Ts.ED
```typescript
import {HTTPException} from "ts-httpexception"
class FunctionalError extends Exception {
   constructor(message, errors: any[]) {
       super(message)
       
      this.errors = errors
   } 
}
```
Then:
```typescript
@Controller('/')
class ExampleCtrl {
   @get('/')
   throwError() {
      throw FunctionalError('MyFunctionalError', [{description:'description'}]);
   }
}
```
The `{description:'description'}` object will be serialized in the `errors: [{"description":"description"}]` header.

See you,
Romain

**Comment by Romakita** [comment]
https://github.com/TypedProject/ts-httpexceptions/pull/5

**Comment by Romakita** [comment]
It should solved your issue :)
